// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcko2ZYetjj2RzTLANy-WeJO_59rSA52c',
    appId: '1:765193476673:web:948875d5a8d0cb3cadc4c0',
    messagingSenderId: '765193476673',
    projectId: 'flutter-sample-tegos',
    authDomain: 'flutter-sample-tegos.firebaseapp.com',
    databaseURL: 'https://flutter-sample-tegos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-sample-tegos.appspot.com',
    measurementId: 'G-HZHXE22M9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5M8JSs10L4wS5wj9lKnVHCFyoXxjdp2o',
    appId: '1:765193476673:android:4a795c6f93cdb46badc4c0',
    messagingSenderId: '765193476673',
    projectId: 'flutter-sample-tegos',
    databaseURL: 'https://flutter-sample-tegos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-sample-tegos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYaqFmojdi7x7wEdXYPcA7DYhcJzsbu1Y',
    appId: '1:765193476673:ios:7b288288d6b06cc9adc4c0',
    messagingSenderId: '765193476673',
    projectId: 'flutter-sample-tegos',
    databaseURL: 'https://flutter-sample-tegos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-sample-tegos.appspot.com',
    iosClientId: '765193476673-228ofgu01hou61ggias3ao57ji7shica.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbs2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYaqFmojdi7x7wEdXYPcA7DYhcJzsbu1Y',
    appId: '1:765193476673:ios:b75a30400c2d84b4adc4c0',
    messagingSenderId: '765193476673',
    projectId: 'flutter-sample-tegos',
    databaseURL: 'https://flutter-sample-tegos-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-sample-tegos.appspot.com',
    iosClientId: '765193476673-ev8sb85jblbg2dgqced939cdg5ons5i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbs2.RunnerTests',
  );
}
